

<div class="container">
    <h1>Prova Alexandre</h1>

        <button class="btn btn-info"><a href="<?=$this->url('usuario', ['action' => 'add']) ?>">Adicionar Usuario</a></button>

    <button class="btn btn-info"><a href="<?=$this->url('usuario', ['action' => 'login']) ?>">Logar</a></button>

         </form>


    <table class="table table-striped">
        <tr>
            <th>Email</th>
            <th>Nome</th>

            <th></th>
        </tr>
        <?php foreach ($usuarios as $user): ?>
            <tr>
                <td><?=$this->escapeHtml($user->email) ?></td>
                <td><?=$this->escapeHtml($user->nome) ?></td>
            </tr>
        <?php endforeach ?>
</div>