<h1>Login</h1>

<?php
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$senha = $form->get('senha');
$senha->setAttribute('class', 'form-control');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$form->setAttribute('action', $this->url('usuario', ['action' =>'login']));
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?=$this->formLabel($email); ?>
    <?=$this->formElement($email); ?>
</div>

<div class="form-group">
    <?=$this->formLabel($senha); ?>
    <?=$this->formElement($senha);?>
</div>
     <?php

    echo $this->formSubmit($submit);
    ?>
    <a href="javascript:history.back(-1)"><button class="btn btn-dark" type="button">Voltar</button></a>
<?php
    echo $this->form()->closeTag();
    ?>
<?php if ($messageError): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>





